name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Habilitar Corepack (pnpm)
        run: corepack enable

      # --- CONFIGURAÇÃO DO CACHE ---
      - name: Obter diretório do store do pnpm
        id: pnpm-cache
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Configurar Cache do pnpm
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      # -----------------------------

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      # --- PASSO ADICIONADO PARA O PRISMA ---
      - name: Gerar Prisma Client
        run: pnpm prisma generate
      # --------------------------------------

      - name: Rodar testes unitários
        run: pnpm test
